# Generated by Django 5.2.16 on 2026-08-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='guest', max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='document', max_length=50)),
                ('file_size', models.CharField(default='0 KB', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
